import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { demoGet } from '../public/demo.js';

const root=new URL('../public/',import.meta.url);
const html=await readFile(new URL('index.html',root),'utf8');
const code=(await readFile(new URL('app.js',root),'utf8')).replace("import { demoGet } from './demo.js';",'const demoGet = window.demoGet;');
const catalog=JSON.parse((await readFile(new URL('scenarios.json',root),'utf8')).replace(/^\uFEFF/,''));
const dom=new JSDOM(html,{url:'http://localhost:8080/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;
w.demoGet=demoGet;
let intervalCalls=0;
w.setInterval=()=>{intervalCalls++;return 0;};
const requests=[];
w.fetch=async (url,opts={})=>{
 requests.push({url,method:opts.method||'GET'});
 if(url==='scenarios.json')return {ok:true,json:async()=>catalog};
 if(url==='/api/ops/capabilities')return {ok:true,json:async()=>({backendImplemented:false,labEnabled:false,dataSource:'UNIMPLEMENTED'})};
 if(url==='/api/ops/schema')return {ok:true,json:async()=>({databaseName:'wallet',schemaName:'public',databaseVersion:'PostgreSQL 16.14, test',observedAt:'2026-10-09T00:00:00Z',tables:[{name:'accounts',type:'BASE TABLE',columns:[{name:'id',dataType:'uuid',nullable:false,defaultValue:null}],constraints:[{name:'accounts_pkey',type:'PRIMARY KEY',columnName:'id',referencedTable:null,referencedColumn:null}]},{name:'transfers',type:'BASE TABLE',columns:[{name:'from_account_id',dataType:'uuid',nullable:false,defaultValue:null}],constraints:[{name:'transfers_from_account_id_fkey',type:'FOREIGN KEY',columnName:'from_account_id',referencedTable:'accounts',referencedColumn:'id'}]}]})};
 return {ok:false,status:501,json:async()=>({message:'Backend chưa triển khai'})};
};
const wait=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('DOM condition timed out');};
const q=s=>w.document.querySelector(s);
const qa=s=>[...w.document.querySelectorAll(s)];
async function go(hash,condition){w.location.hash=hash;await wait(condition);}
w.eval(code);
await wait(()=>q('#content').textContent.includes('Chưa lấy được dữ liệu thật'));
assert.equal(q('#source-label').textContent,'API THẬT');
assert(!q('#notice').textContent.includes('DỮ LIỆU MINH HỌA'));
console.log('PASS: API 501 remains a real error, without implicit demo fallback');
q('#mode-toggle').click();
await wait(()=>q('#content').textContent.includes('Bất biến tiền'));
assert.equal(qa('.check-row').length,8);
assert.equal(qa('.check-row.fail').length,2);
assert(q('#notice').textContent.includes('DỮ LIỆU MINH HỌA'));
assert.equal(q('#auto-refresh'),null);
assert.equal(intervalCalls,0);
console.log('PASS: explicit demo mode, eight invariant checks and mismatch drilldown');
await go('transfers',()=>!!q('#transfer-filter'));
assert.equal(qa('tbody tr').length,3);
q('[name=status]').value='UNKNOWN';
q('#transfer-filter').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
await wait(()=>qa('tbody tr').length===1&&w.location.hash.includes('status=UNKNOWN'));
q('tbody a').click();
await wait(()=>q('#content').textContent.includes('Dòng thời gian'));
assert.equal(qa('.timeline li').length,6);
assert(q('#content').textContent.includes('Cùng khóa retry'));
console.log('PASS: transfer filters → timeline, T postings and bank retry key');
await go('accounts?mismatchedOnly=true',()=>!!q('#account-filter'));
assert.equal(qa('tbody tr').length,1);
q('tbody a').click();
await wait(()=>q('#content').textContent.includes('Sổ phụ tài khoản')&&!!q('svg'));
assert.equal(qa('tbody tr').length,3);
assert(q('#content').textContent.includes('Lệch số dư'));
console.log('PASS: account mismatch filtering → statement and step chart');
await go('queues',()=>q('#content').textContent.includes('Outbox chưa gửi'));
assert.equal(qa('[data-chaos]').length,8);
assert(qa('[data-chaos]').every(b=>b.disabled));
await go('reconciliation',()=>!!q('#issue-filter'));
assert(q('#content').textContent.includes('BALANCE_CACHE_MISMATCH'));
assert(q('#content').textContent.includes('50.500'));
console.log('PASS: queues, signature warnings, read-only chaos and reconciliation evidence');
await go('lab',()=>qa('[data-run]').length===36);
assert(q('#content').textContent.includes('Bạn không cần tự tạo giao dịch'));
assert.equal(qa('[data-experiment]').length,5);
assert(qa('[data-experiment]').every(b=>b.disabled));
assert.equal(qa('[data-experiment]').filter(b=>b.closest('.scenario').querySelector('details')?.textContent.includes('Code đang tồn tại:')).length,5);
assert(q('[data-experiment="V0-PARTIAL-WRITE"]').closest('.scenario').textContent.includes('TransferServiceImpl.create'));
assert(q('[data-experiment="V0-PARTIAL-WRITE"]').closest('.scenario').textContent.includes('LocalTransferFaults.failIfArmed'));
assert.equal(qa('[data-run]').length,36);
assert(qa('[data-run]').every(b=>b.disabled));
assert.equal(qa('[data-run]').filter(b=>b.closest('.scenario').querySelector('details')?.textContent.includes('Luồng dự kiến (chưa có code):')).length,36);
assert(q('[data-run="A1"]').closest('.scenario').textContent.includes('Bắt đầu nâng cấp từ đâu:'));
assert(q('#reset').disabled);
assert(q('#reset-seed').disabled);
assert.equal(qa('[data-chaos]').length,8);
q('[data-group=C]').click();
await wait(()=>qa('[data-run]').length===8);
assert(qa('[data-run]').every(x=>x.dataset.run.startsWith('C')));
q('[data-run]').closest('.scenario').querySelector('details').open=true;
assert(q('[data-run]').closest('.scenario').querySelector('details').textContent.includes('CRASH_AT='));
assert(q('[data-run]').closest('.scenario').querySelector('details').textContent.includes('chưa có code'));
console.log('PASS: all cards explain existing/planned call flows, group filtering and disabled write controls');
q('a[href^="#runs/"]').click();
await wait(()=>q('#content').textContent.includes('Ảnh chụp trước → sau'));
assert.equal(qa('.snapshot pre').length,2);
assert(q('#content').textContent.includes('50500'));
console.log('PASS: run history → assertions, actual/expected and before/after snapshots');
await go('schema',()=>qa('.schema-table').length===2);
assert(q('#content').textContent.includes('METADATA THẬT'));
assert(q('#content').textContent.includes('transfers_from_account_id_fkey'));
assert.equal(q('#source-label').textContent,'API THẬT');
console.log('PASS: schema page renders live database metadata and foreign-key relationships');
await go('transfers?search=%22%3E%3Cimg%20src%3Dx%20onerror%3Dalert(1)%3E',()=>!!q('#transfer-filter'));
assert.equal(qa('#content img').length,0);
assert(q('[name=search]').value.includes('<img'));
assert.equal(requests.filter(r=>r.method!=='GET').length,0);
console.log('PASS: search text is escaped; no write request from demo interactions');
q('#mode-toggle').click();
await wait(()=>!q('#error').hidden);
assert.equal(q('#source-label').textContent,'API THẬT');
assert(q('#content').textContent.includes('Chưa lấy được dữ liệu thật'));
console.log('PASS: returning to live mode reports the stub instead of retaining demo values');
dom.window.close();


