spring:
  application:
    name: ops-service
server:
  address: 127.0.0.1
  port: ${OPS_PORT:8082}
wallet:
  url: ${WALLET_URL:http://127.0.0.1:8080}
bank:
  url: ${BANK_URL:http://127.0.0.1:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info
