spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    validate-on-migrate: true
    validate-migration-naming: true
    baseline-on-migrate: false
    clean-disabled: true
