spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  profiles:
    default:
      - db
      - db-seed
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://${WALLET_DB_HOST:localhost}:${WALLET_DB_PORT:5433}/${WALLET_DB_NAME:wallet}
    username: ${WALLET_DB_USERNAME:wallet}
    password: ${WALLET_DB_PASSWORD:wallet-local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/seed/scripts
    default-schema: public
    validate-on-migrate: true
    validate-migration-naming: true
    baseline-on-migrate: false
    clean-disabled: true
server:
  port: ${WALLET_PORT:8080}
bank:
  url: ${BANK_URL:http://localhost:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info
